### ISSUE TITLE
Error when editing channel

### ISSUE THREAD

**Issue by marvin52** [feedcast/core#7]
![image](https://user-images.githubusercontent.com/2734828/29753895-f02a7c4e-8b50-11e7-9c69-7fc174b8ac08.png)

i got this error when i was trying to edit this channel  and saving http://api.feedcast.io/admin/channel/5894cf0ac1eb520005e246ff/edit

**Comment by marceloboeira** [comment]
Can you send the message or the screenshot here?

**Comment by marvin52** [comment]
```
2017-08-27T21:25:15.907647+00:00 app[web.1]: I, [2017-08-27T21:25:15.907539 #5]  INFO -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] Started POST "/admin/channel/58726426fd797700052a984e/edit" for 172.68.26.77 at 2017-08-27 21:25:15 +0000
2017-08-27T21:25:15.914012+00:00 app[web.1]: F, [2017-08-27T21:25:15.913936 #5] FATAL -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8]   
2017-08-27T21:25:15.914088+00:00 app[web.1]: F, [2017-08-27T21:25:15.914023 #5] FATAL -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] ActionController::RoutingError (No route matches [POST] "/admin/channel/58726426fd797700052a984e/edit"):
2017-08-27T21:25:15.914178+00:00 app[web.1]: F, [2017-08-27T21:25:15.914113 #5] FATAL -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8]   
2017-08-27T21:25:15.914269+00:00 app[web.1]: F, [2017-08-27T21:25:15.914200 #5] FATAL -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
2017-08-27T21:25:15.914270+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/rollbar-2.15.0/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
2017-08-27T21:25:15.914271+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914272+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
2017-08-27T21:25:15.914273+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914274+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:36:in `call_app'
2017-08-27T21:25:15.914275+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `block in call'
2017-08-27T21:25:15.914275+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
2017-08-27T21:25:15.914276+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-08-27T21:25:15.914276+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `tagged'
2017-08-27T21:25:15.914277+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/rack/logger.rb:24:in `call'
2017-08-27T21:25:15.914277+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914278+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
2017-08-27T21:25:15.914278+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914279+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/request_id.rb:25:in `call'
2017-08-27T21:25:15.914279+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914279+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
2017-08-27T21:25:15.914280+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914280+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/executor.rb:12:in `call'
2017-08-27T21:25:15.914281+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914281+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.3/lib/action_dispatch/middleware/static.rb:125:in `call'
2017-08-27T21:25:15.914281+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914282+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/engine.rb:522:in `call'
2017-08-27T21:25:15.914282+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.3.0.335/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
2017-08-27T21:25:15.914283+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
2017-08-27T21:25:15.914283+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
2017-08-27T21:25:15.914283+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
2017-08-27T21:25:15.914284+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
2017-08-27T21:25:15.914285+00:00 app[web.1]: [01fc2732-6dca-45ea-bb9e-8721cd894ea8] vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2017-08-27T21:25:15.914572+00:00 app[web.1]: D, [2017-08-27T21:25:15.914506 #5] DEBUG -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] [Rollbar] Reporting exception: No route matches [POST] "/admin/channel/58726426fd797700052a984e/edit"
2017-08-27T21:25:15.924131+00:00 app[web.1]: I, [2017-08-27T21:25:15.924069 #5]  INFO -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] [Rollbar] Scheduling item
2017-08-27T21:25:15.924179+00:00 app[web.1]: I, [2017-08-27T21:25:15.924134 #5]  INFO -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] [Rollbar] Sending item
2017-08-27T21:25:15.986986+00:00 app[web.1]: I, [2017-08-27T21:25:15.986881 #5]  INFO -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] [Rollbar] Success
2017-08-27T21:25:15.987038+00:00 app[web.1]: I, [2017-08-27T21:25:15.986986 #5]  INFO -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=7a58f81f-66f2-433e-b756-cb99f3382b68 (only available if report was successful)
2017-08-27T21:25:15.987099+00:00 app[web.1]: D, [2017-08-27T21:25:15.987054 #5] DEBUG -- : [01fc2732-6dca-45ea-bb9e-8721cd894ea8] [Rollbar] Exception uuid saved in env: 7a58f81f-66f2-433e-b756-cb99f3382b68
```

**Comment by marceloboeira** [comment]
@marvin52 fixed! Thanks for reporting!
